<?php
namespace app\api\controller;


use think\Controller;

class Category extends Controller
{
    private $db;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->db=model('Category');
    }

    public function category()
    {
        $id=input('post.id');
        //halt($id);
        $result=$this->db->category_view($id);
        //halt($result);
        if($result)
        {
            return  show('1','success',$result);
        }
        else
        {
            return $this->error('数据错误');
        }
    }
}