<?php
namespace app\api\controller;

use think\Controller;

class City extends Controller
{
    private $db;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->db=model('City');
    }

    public function city()
{
    $id=input('post.id');
    //halt($id);
    $result=$this->db->city($id);
    //halt($result);
    if($result)
    {
        return  show('1','success',$result);
    }
    else
    {
        return $this->error('数据错误');
    }
}
}